name: Release
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CIBW_TEST_COMMAND: |
    python -m krypton --clean
    python -m unittest discover -s {project}/tests -p "*test*.py" --verbose

jobs:
  buildLinuxMultiArch:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
    env:
      CIBW_ARCHS: ${{ matrix.arch }}
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=/project/kr-openssl-install/lib64:/project/kr-openssl-install/lib
      CIBW_TEST_SKIP: pp* # We do not test PyPy because we don't want to compile cryptography - which is needed for tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            cd /project
            yum install -y perl-IPC-Cmd
            yum install -y make
            mkdir kr-openssl-config
            mkdir kr-openssl-install
            cd openssl
            perl Configure linux-${{ matrix.arch }} --prefix=/project/kr-openssl-install --openssldir=/project/kr-openssl-config enable-fips
            make -j3
            make -j3 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildWin:
    env:
      CIBW_ARCHS: native
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: NASM and Perl
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          py -m pip install --upgrade pip setuptools wheel
      - name: Build OSSL
        env:
          CL: /MP
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*
  buildWinARM:
    env:
      CIBW_ARCHS: ARM64
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_arm64
      - name: NASM and Perl
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          mkdir kr-openssl-install
          mkdir kr-openssl-config
          python -m pip install --upgrade pip setuptools wheel
      - name: Build OSSL
        env:
          CL: /MP
        run: |
          cd openssl
          perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildMac:
    env:
      CIBW_ARCHS: native
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=${{ github.workspace }}/kr-openssl-install/lib
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            cd openssl
            perl Configure --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
            make -j4
            make -j4 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-MacOS-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildMacARM:
    env:
      CIBW_ARCHS: arm64
      CIBW_ENVIRONMENT: LD_LIBRARY_PATH=${{ github.workspace }}/kr-openssl-install/lib
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build Extension
        run: |
          python3 -m pip install cibuildwheel
          python3 -m cibuildwheel --output-dir dist
        env:
          CIBW_BEFORE_ALL: |
            cd openssl
            perl Configure darwin64-arm64 --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
            make -j4
            make -j4 install
            cd ..
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-MacOS-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildWin32:
    env:
      CIBW_ARCHS: x86
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install VS Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: NASM and Perl
        run: |
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          choco install strawberryperl
      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}
          py -m pip install --upgrade pip setuptools wheel
      - name: Build OSSL
        env:
          CL: /MP
        run: |
          cd openssl
          perl Configure VC-WIN32 --prefix=${{ github.workspace }}/kr-openssl-install --openssldir=${{ github.workspace }}/kr-openssl-config enable-fips
          nmake
          nmake install
      - name: Build Extension
        run: |
          cd ${{ github.workspace }}
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir dist
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist/*.*

  buildSourceDist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: "true"
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build
      run: |
        pip install -r requirements.txt
        cp -r sample-kr-openssl-config kr-openssl-config
        python setup.py sdist
    - name: Upload Build Result
      uses: actions/upload-artifact@v3
      with:
        name: AutoBuild-Source-${{ github.event.release.tag_name }}
        path: ${{ github.workspace }}/dist/*.*

  releaseBins:
    if: github.event_name == 'release'
    env:
      GH_TOKEN: ${{ secrets.App }}
    runs-on: ubuntu-latest
    needs: [buildLinuxMultiArch, buildWin, buildWinARM, buildMac, buildMacARM, buildWin32, buildSourceDist]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Create Dir for Build
        run: |
          cd ${{ github.workspace }}
          mkdir dist
      - name: Download Built Windows Extensions
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Windows-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Download Built Linux Extension
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Linux-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Download Built MacOS Extension
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-MacOS-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Download Built Sdist Extension
        uses: actions/download-artifact@v3
        with:
          name: AutoBuild-Source-${{ github.event.release.tag_name }}
          path: ${{ github.workspace }}/dist
      - name: Upload Build Results to GH Release
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.*
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
#          repository_url: https://test.pypi.org/legacy/
