name: TestRelease
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CIBW_TEST_COMMAND: |
    python -m krypton --clean
    python -m unittest discover -s {project}/tests -p "*test*.py" --verbose

jobs:
  buildLinuxArm:
      env:
        CIBW_ARCHS: aarch64
        CIBW_TEST_SKIP: pp* # We do not test PyPy because we don't want to compile cryptography - which is needed for tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
          with:
            submodules: "true"
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: arm64
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip setuptools wheel
        - name: Build Extension
          run: |
            python3 -m pip install cibuildwheel
            python3 -m cibuildwheel --output-dir dist
          env:
            CIBW_ENVIRONMENT: VCPKG_FORCE_SYSTEM_BINARIES=1
            CIBW_BEFORE_ALL: |
              yum install -y curl zip unzip tar make gcc gcc-c++
              curl -o setupCmake.sh -sSSL https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-linux-aarch64.sh
              chmod a+rx setupCmake.sh
              ./setupCmake.sh --skip-license --exclude-subdir
              export PATH="{package}/bin:$PATH"
              git clone https://github.com/ninja-build/ninja.git && cd ninja
              git checkout release
              cmake -Bbuild-cmake
              cmake --build build-cmake
              cd ..
              cp -r ninja/build-cmake/* bin/
              ./vcpkg/bootstrap-vcpkg.sh
              ./vcpkg/vcpkg install --triplet arm64-linux
        - name: Upload Build Result
          uses: actions/upload-artifact@v3
          with:
            name: AutoBuild-Linux-${{ github.event.release.tag_name }}
            path: ${{ github.workspace }}/dist/*.*